export const Characters = [
  {
    id: "11",
    name: "Camisa de jeans",
    description: "Lorem ipsum dolor sit amet, " ,
    type: "h",
  },
  {
    id: "12",
    name: "Formal y negro",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },
  {
    id: "13",
    name: " Cuero y jeans toturas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "h",
  },
  {
    id: "14",
    name: "Camisa informal",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },
  {
    id: "15",
    name: "Campera informal",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "h",
  },
  {
    id: "16",
    name: "Ofice informal",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },

  {
    id: "17",
    name: "Tapado botas grises",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },
  {
    id: "18",
    name: "Remera y jeans",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },
  {
    id: "19",
    name: "Chomba y vermudas",
    description: "Lorem ipsum dolor sit amet, ",
    type: "h",
  },
  {
    id: "20",
    name: "Casual informal",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "h",
  },
  {
    id: "1",
    name: "Deportivo blancos y cartera ",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "2",
    name: "Informal remera y botas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "3",
    name: "Casual informal",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "4",
    name: "Casual jeans",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "5",
    name: "Sacon y botas Ofice",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },

  {
    id: "6",
    name: "Casual verano",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
{
    id: "7",
    name: "Pantalon informal",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "8",
    name: "Jeans con roturas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "9",
    name: "Pantalon ancho",
    description: "Lorem ipsum dolor sit amet, ",
    type: "m",
  },
  {
    id: "10",
    name: "Chaleco jeans roturas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "m",
  },
  {
    id: "21",
    name: "Negro y gris",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "22",
    name: "Formal fiesta",
    description: "Lorem ipsum dolor sit amet, ",
    type: "k",
  },
  {
    id: "23",
    name: "Remera y vermuda",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "24",
    name: "Camisa y vermudas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "25",
    name: "Rojo y gafas",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "26",
    name: "Jeans y camisa", 
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "27",
    name: "Pollera y sweter",
    description: "Lorem ipsum dolor sit amet, ",
    type: "k",
  },
  {
    id: "28",
    name: "Negro formal",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "29",
    name: "Vestido gris",
    description: "Lorem ipsum dolor sit amet,  ",
    type: "k",
  },
  {
    id: "30",
    name: "Vestido bordo",
    description: "Lorem ipsum dolor sit amet,",
    type: "k",
  },
];
